name: Build Paper PDF
on: [push]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build draft PDF using Docker
        uses: docker://openjournals/paperdraft:latest
        with:
          args: "-p paper.md"
        env:
          JOURNAL: joss

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
